### ISSUE TITLE
Error TS1005: ';' expected

### ISSUE THREAD

**Issue by FaganSC** [mkhstar/suneditor-react#228]
Trying to update my solution to 3.2.0 and getting the following errors with the SunEditor-React package
![image](https://user-images.githubusercontent.com/810028/126007756-dc48eb97-4b70-49a3-b0a4-f3b812da6f85.png)

Any thoughts?

**Comment by mkhstar** [comment]
@FaganSC 
Can you open a more specific issue. Because I don't know how you came up with this.

**Comment by FaganSC** [comment]
@mkhstar came up after installing the newest version of Suneditor-React into my SharePoint framework solution. It's currently using version 2.16.5 without issue inside my solution. When I upgraded to 3.2.0, and simply tried to build the solution, that is the errors I received.  It's a React 16.9.0 solutions.

**Comment by EwaMlynarczyk** [comment]
I have the same errors in my SPFX. Newer version of Suneditors required typescript version 4.x, but SPFX provides , as for now, just 3.7 :(
What did help to get rid of the errors is to install version: "suneditor-react": "2.16.5".
Errors don't popup anymore, but all in all, inserting pure editor onto my page ends with:
![image](https://user-images.githubusercontent.com/69498773/128325286-dc3208b7-f039-4912-9728-206b99c69ed3.png)

:/

**Comment by EwaMlynarczyk** [comment]
I guess the problem is that the newest version of Suneditor requries typescript 4.x, and  the newest available spfx provides us with typescript 3.7
