### ISSUE TITLE
Image upload issue in verssion 3.5.0

### ISSUE THREAD

**Issue by UnikoveNeeraj** [mkhstar/suneditor-react#312]
Image upload is not working in latest version 3.5.0. Its giving error-
image.js:383 Uncaught Error: [SUNEDITOR.image.submit.fail] cause : "uploadHandler is not a function"
    at Object.submit (image.js:383:1)
    
  Please suggest is any event or functional call changed in latest version.
  Its working fine 3.4.1

**Comment by mkhstar** [comment]
Thanks for opening the issue. The latest version 3.6.1 should resolve the issue. The order of the params were causing the issue
